env:
  PLAYWRIGHT_VERSION: 1.57.0
  PACKAGE_ID: headful-chromium
on:
  push:
    branches:
      - master
    paths:
      - .github/workflows/headful-chromium.yml
      - packages/headful-chromium/**
jobs:
  deploy:
    runs-on: ubuntu-latest
    outputs:
      PACKAGE_ID: ${{ steps.e.outputs.PACKAGE_ID }}
    steps:
    - id: e
      run: |
        echo "PACKAGE_ID=${{env.PACKAGE_ID}}" >> "$GITHUB_OUTPUT"
    - uses: actions/checkout@v4
    - uses: docker/setup-qemu-action@v3
    - uses: docker/setup-buildx-action@v3
    - uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - id: meta_debian11
      uses: docker/metadata-action@v5
      with:
        images: |
          sstc/${{ env.PACKAGE_ID }}
        tags: |
          type=raw,value=debian-11
    - uses: docker/build-push-action@v6
      with:
        context: ./packages/${{ env.PACKAGE_ID }}
        push: true
        platforms: linux/amd64,linux/arm64
        file: ./packages/${{ env.PACKAGE_ID }}/debian-11/Dockerfile
        tags: ${{ steps.meta_debian11.outputs.tags }}
        build-args: |
          PLAYWRIGHT_VERSION=${{env.PLAYWRIGHT_VERSION}}
    - id: meta_debian12
      uses: docker/metadata-action@v5
      with:
        images: |
          sstc/${{ env.PACKAGE_ID }}
        tags: |
          type=raw,value=debian
          type=raw,value=debian-12
    - uses: docker/build-push-action@v6
      with:
        context: ./packages/${{ env.PACKAGE_ID }}
        push: true
        platforms: linux/amd64,linux/arm64
        file: ./packages/${{ env.PACKAGE_ID }}/debian-12/Dockerfile
        tags: ${{ steps.meta_debian12.outputs.tags }}
        build-args: |
          PLAYWRIGHT_VERSION=${{env.PLAYWRIGHT_VERSION}}
    - id: meta_ubuntu22
      uses: docker/metadata-action@v5
      with:
        images: |
          sstc/${{ env.PACKAGE_ID }}
        tags: |
          type=raw,value=ubuntu-22
    - uses: docker/build-push-action@v6
      with:
        context: ./packages/${{ env.PACKAGE_ID }}
        push: true
        platforms: linux/amd64,linux/arm64
        file: ./packages/${{ env.PACKAGE_ID }}/ubuntu-22/Dockerfile
        tags: ${{ steps.meta_ubuntu22.outputs.tags }}
        build-args: |
          PLAYWRIGHT_VERSION=${{env.PLAYWRIGHT_VERSION}}
    - id: meta_ubuntu24
      uses: docker/metadata-action@v5
      with:
        images: |
          sstc/${{ env.PACKAGE_ID }}
        tags: |
          type=raw,value=latest
          type=raw,value=ubuntu
          type=raw,value=ubuntu-24
    - uses: docker/build-push-action@v6
      with:
        context: ./packages/${{ env.PACKAGE_ID }}
        push: true
        platforms: linux/amd64,linux/arm64
        file: ./packages/${{ env.PACKAGE_ID }}/ubuntu-24/Dockerfile
        tags: ${{ steps.meta_ubuntu24.outputs.tags }}
        build-args: |
          PLAYWRIGHT_VERSION=${{env.PLAYWRIGHT_VERSION}}
    - uses: christian-korneck/update-container-description-action@v1
      env:
        DOCKER_USER: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKER_PASS: ${{ secrets.DOCKERHUB_PASSWORD }}
      with:
        destination_container_repo: sstc/${{ env.PACKAGE_ID }}
        short_description: https://github.com/${{ github.repository }}/packages/${{ env.PACKAGE_ID }}
        readme_file: './packages/${{ env.PACKAGE_ID }}/README.md'
  notify:
    if: cancelled() == false
    needs: deploy
    secrets: inherit
    uses: ./.github/workflows/_notify.yml
    with:
      conclusion: ${{ needs.deploy.result }}
      package: ${{ needs.deploy.outputs.PACKAGE_ID }}
