env:
  PLAYWRIGHT_VERSION: 1.57.0
  PACKAGE_NAME: headful-chromium
on:
  push:
    branches:
      - master
    paths:
      - .github/workflows/headful-chromium.yml
      - packages/headful-chromium/**
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: docker/setup-qemu-action@v3
    - uses: docker/setup-buildx-action@v3
    - uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - id: meta_debian11
      uses: docker/metadata-action@v5
      with:
        images: |
          sstc/${{ env.PACKAGE_NAME }}
        tags: |
          type=raw,value=debian-11
    - uses: docker/build-push-action@v6
      with:
        push: true
        platforms: linux/amd64,linux/arm64
        file: ./packages/${{ env.PACKAGE_NAME }}/debian-11/Dockerfile
        tags: ${{ steps.meta_debian11.outputs.tags }}
        build-args: |
          PLAYWRIGHT_VERSION=${{env.PLAYWRIGHT_VERSION}}
    - id: meta_debian12
      uses: docker/metadata-action@v5
      with:
        images: |
          sstc/${{ env.PACKAGE_NAME }}
        tags: |
          type=raw,value=debian
          type=raw,value=debian-12
    - uses: docker/build-push-action@v6
      with:
        push: true
        platforms: linux/amd64,linux/arm64
        file: ./packages/${{ env.PACKAGE_NAME }}/debian-12/Dockerfile
        tags: ${{ steps.meta_debian12.outputs.tags }}
        build-args: |
          PLAYWRIGHT_VERSION=${{env.PLAYWRIGHT_VERSION}}
    - id: meta_ubuntu22
      uses: docker/metadata-action@v5
      with:
        images: |
          sstc/${{ env.PACKAGE_NAME }}
        tags: |
          type=raw,value=ubuntu-22
    - uses: docker/build-push-action@v6
      with:
        push: true
        platforms: linux/amd64,linux/arm64
        file: ./packages/${{ env.PACKAGE_NAME }}/ubuntu-22/Dockerfile
        tags: ${{ steps.meta_ubuntu22.outputs.tags }}
        build-args: |
          PLAYWRIGHT_VERSION=${{env.PLAYWRIGHT_VERSION}}
    - id: meta_ubuntu24
      uses: docker/metadata-action@v5
      with:
        images: |
          sstc/${{ env.PACKAGE_NAME }}
        tags: |
          type=raw,value=latest
          type=raw,value=ubuntu
          type=raw,value=ubuntu-24
    - uses: docker/build-push-action@v6
      with:
        push: true
        platforms: linux/amd64,linux/arm64
        file: ./packages/${{ env.PACKAGE_NAME }}/ubuntu-24/Dockerfile
        tags: ${{ steps.meta_ubuntu24.outputs.tags }}
        build-args: |
          PLAYWRIGHT_VERSION=${{env.PLAYWRIGHT_VERSION}}
    - uses: christian-korneck/update-container-description-action@v1
      env:
        DOCKER_USER: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKER_PASS: ${{ secrets.DOCKERHUB_PASSWORD }}
      with:
        destination_container_repo: sstc/${{ env.PACKAGE_NAME }}
        short_description: https://github.com/${{ github.repository }}/packages/${{ env.PACKAGE_NAME }}
        readme_file: './packages/${{ env.PACKAGE_NAME }}/README.md'
    - uses: up9cloud/action-notify@master
      if: cancelled() == false
      env:
        GITHUB_JOB_STATUS: ${{ job.status }}
        TELEGRAM_BOT_TOKEN: ${{secrets.TELEGRAM_BOT_TOKEN}}
        TELEGRAM_CHAT_ID: ${{secrets.TELEGRAM_CHAT_ID}}
