env:
  PACKAGE_ID: notify
on:
  push:
    paths:
      - .github/workflows/notify.yml
      - packages/notify/**
jobs:
  deploy:
    runs-on: ubuntu-latest
    outputs:
      PACKAGE_ID: ${{ steps.e.outputs.PACKAGE_ID }}
    steps:
    - id: e
      run: |
        echo "PACKAGE_ID=${{env.PACKAGE_ID}}" >> "$GITHUB_OUTPUT"
    - uses: actions/checkout@v4
    - uses: docker/setup-qemu-action@v3
    - uses: docker/setup-buildx-action@v3
    - uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - uses: docker/build-push-action@v4
      with:
        context: ./packages/${{ env.PACKAGE_ID }}
        push: true
        platforms: linux/amd64,linux/arm64
        file: ./packages/${{ env.PACKAGE_ID }}/Dockerfile
        tags: sstc/${{ env.PACKAGE_ID }}:latest
    - uses: christian-korneck/update-container-description-action@v1
      env:
        DOCKER_USER: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKER_PASS: ${{ secrets.DOCKERHUB_PASSWORD }}
      with:
        destination_container_repo: sstc/${{ env.PACKAGE_ID }}
        short_description: https://github.com/${{ github.repository }}/tree/master/packages/${{ env.PACKAGE_ID }}
        readme_file: './packages/${{ env.PACKAGE_ID }}/README.md'
  notify:
    if: cancelled() == false
    needs: deploy
    secrets: inherit
    uses: ./.github/workflows/_notify.yml
    with:
      conclusion: ${{ needs.deploy.result }}
      package: ${{ needs.deploy.outputs.PACKAGE_ID }}
